import "./neo-avatars";
import "./neo-breadcrumb";
import "./neo-button";
import "./neo-buttongroup";
import "./neo-carousel";
import "./neo-checkbox";
import "./neo-clipcopy";
import "./neo-color-field";
import "./neo-combobox";
import "./neo-condition";
import "./neo-contextmenu";
import "./neo-datalist";
import "./neo-dialog";
import "./neo-drawer";
import "./neo-elastic";
import "./neo-icon";
import "./neo-input-group";
import "./neo-kbd";
import "./neo-keys";
import "./neo-lightbox";
import "./neo-menu";
import "./neo-menuitem";
import "./neo-navgroup";
import "./neo-pagination";
import "./neo-persist";
import "./neo-popover";
import "./neo-progress";
import "./neo-radio-group";
import "./neo-rating";
import "./neo-resizable";
import "./neo-revealable";
import "./neo-select";
import "./neo-sidebar";
import "./neo-slider";
import "./neo-slider-range";
import "./neo-sortable";
import "./neo-spinner";
import "./neo-submenu";
import "./neo-switch";
import "./neo-tabs";
import "./neo-textarea";
import "./neo-textinput";
import "./neo-toast";
import "./neo-toaster";
import "./neo-toggle";
import "./neo-toggle-group";
import "./neo-tooltip";
import "./neo-tree";
import { watchMissingComponents } from "./missing-components";

// Registration of all components above is synchronous, so this runs after
// the bundle's full set is defined and can flag any <neo-*> the bundle omits.
watchMissingComponents();
