// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package neo

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// KeysOpts: see <neo-keys> attributes. Binds keyboard shortcuts in the
// scope of a target element (its parent by default) and emits an event
// on a match. Renders nothing.
type KeysOpts struct {
	Keys            Attr[string] // chords; `+` joins, `,` sequences, `|` alternatives
	Target          Attr[string] // parent | window | document | CSS selector
	For             Attr[string] // element id to click on a match
	Up              Attr[bool]   // match on keyup instead of keydown
	Repeat          Attr[bool]   // allow auto-repeat to fire
	Prevent         Attr[bool]   // Set(false) emits prevent="false" to keep the default action
	Stop            Attr[bool]   // stopPropagation on a match
	InInput         Attr[bool]   // also fire from text-entry contexts
	Disabled        Attr[bool]   // inert while set
	SequenceTimeout Attr[int]    // ms between sequence steps (default 1000)
}

func keysAttrs(opts KeysOpts, extra templ.Attributes) templ.Attributes {
	a := templ.Attributes{}
	fields := []templ.Attributes{
		opts.Keys.Attrs("keys"),
		opts.Target.Attrs("target"),
		opts.For.Attrs("for"),
		opts.Up.Attrs("up"),
		opts.Repeat.Attrs("repeat"),
		opts.Prevent.Attrs("prevent"),
		opts.Stop.Attrs("stop"),
		opts.InInput.Attrs("in-input"),
		opts.Disabled.Attrs("disabled"),
		opts.SequenceTimeout.Attrs("sequence-timeout"),
	}
	for _, f := range fields {
		for k, v := range f {
			a[k] = v
		}
	}
	for k, v := range extra {
		a[k] = v
	}
	return a
}

// Keys binds keyboard shortcuts scoped to opts.Target (its parent by
// default).
func Keys(opts KeysOpts) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = KeysAttrs(opts, nil).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// KeysAttrs is the form taking extra attributes (e.g. data-on:* event
// handlers, data-attr:disabled). Caller attrs win on collision.
func KeysAttrs(opts KeysOpts, attrs templ.Attributes) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<neo-keys")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, keysAttrs(opts, attrs))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "></neo-keys>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
